apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  serviceAccountName: pod-reader-sa
  containers:
  - name: kubectl-shell
    image: bitnami/kubectl:latest
    command: ["sleep"]
    args: ["3600"]
    stdin: true
    tty: true